// Code generated by genmodel. DO NOT EDIT.

package data

type User struct {
	BaseModel
	Username string `gorm:"column:username;size:64"`
	Password string `gorm:"column:password;size:256"`
	Email    string `gorm:"column:email;size:128"`
	Phone    string `gorm:"column:phone;size:32"`
	Nickname string `gorm:"column:nickname;size:64"`
	Avatar   string `gorm:"column:avatar;size:256"`
	Status   int32  `gorm:"column:status"`
}

func (User) TableName() string {
	return "users"
}
