// Code generated by genmodel. DO NOT EDIT.

package data

import (
	"context"
	"fmt"
	"time"

	"github.com/go-kratos/kratos-layout-monolith/internal/moduser/biz"
	"github.com/go-kratos/kratos/v2/log"
	"gorm.io/gorm"
	"github.com/go-kratos/kratos-layout-monolith/internal/pkg/cache"
)

const (
	userCachePrefix = "users:"
	userCacheTTL    = 2 * time.Hour
	userCacheJitter = 30 * time.Minute
)

type userRepo struct {
	db    *gorm.DB
	redis *cache.Redis
	log   *log.Helper
}

func newUserRepo(db *gorm.DB, rds *cache.Redis, logger log.Logger) *userRepo {
	return &userRepo{
		db:    db,
		redis: rds,
		log:   log.NewHelper(logger),
	}
}

func (r *userRepo) modelCacheKeys(data *User) []string {
	keys := []string{
		fmt.Sprintf("%sid:%v", userCachePrefix, data.Id),
	}
	keys = append(keys, fmt.Sprintf("users:username:%v", data.Username))
	keys = append(keys, fmt.Sprintf("users:email:%v", data.Email))
	return keys
}

func toBizUser(u *User) *biz.User {
	return &biz.User{
		Id: u.Id,
		Username: u.Username,
		Email: u.Email,
		Phone: u.Phone,
		Nickname: u.Nickname,
		Avatar: u.Avatar,
		Status: u.Status,
		CreatedAt: u.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt: u.UpdatedAt.Format("2006-01-02 15:04:05"),
	}
}

func fromBizUser(u *biz.User) *User {
	return &User{
		Id: u.Id,
		Username: u.Username,
		Email: u.Email,
		Phone: u.Phone,
		Nickname: u.Nickname,
		Avatar: u.Avatar,
		Status: u.Status,
		CreatedAt: mustParseTime(u.CreatedAt),
		UpdatedAt: mustParseTime(u.UpdatedAt),
	}
}

func mustParseTime(s string) time.Time {
	t, _ := time.ParseInLocation("2006-01-02 15:04:05", s, time.Local)
	return t
}

func (r *userRepo) CreateUser(ctx context.Context, u *biz.User) (*biz.User, error) {
	user := fromBizUser(u)
	if err := r.db.WithContext(ctx).Create(user).Error; err != nil {
		return nil, err
	}
	r.redis.Set(ctx, fmt.Sprintf("%sid:%v", userCachePrefix, user.Id), user, userCacheTTL)
	r.redis.Set(ctx, fmt.Sprintf("users:username:%v", user.Username), user, userCacheTTL)
	r.redis.Set(ctx, fmt.Sprintf("users:email:%v", user.Email), user, userCacheTTL)
	return toBizUser(user), nil
}

func (r *userRepo) UpdateUser(ctx context.Context, u *biz.User) (*biz.User, error) {
	// read-before-write: get old record to invalidate old cache keys
	old := &User{}
	if err := r.db.WithContext(ctx).First(old, u.Id).Error; err != nil {
		return nil, err
	}
	oldKeys := r.modelCacheKeys(old)

	if err := r.db.WithContext(ctx).Model(&User{ Id: u.Id }).Updates(map[string]any{
		"username": u.Username,
		"email": u.Email,
		"phone": u.Phone,
		"nickname": u.Nickname,
		"avatar": u.Avatar,
		"status": u.Status,
	}).Error; err != nil {
		return nil, err
	}
	r.redis.Del(ctx, oldKeys...)

	// fetch updated record and re-cache
	new := &User{}
	if err := r.db.WithContext(ctx).First(new, u.Id).Error; err != nil {
		return nil, err
	}
	for _, key := range r.modelCacheKeys(new) {
		r.redis.Set(ctx, key, new, userCacheTTL)
	}
	return toBizUser(new), nil
}

func (r *userRepo) GetUserByID(ctx context.Context, id int64) (*biz.User, error) {
	var user User
	err := r.redis.Take(ctx, fmt.Sprintf("%sid:%v", userCachePrefix, id), &user, userCacheTTL, func() error {
		return r.db.WithContext(ctx).First(&user, id).Error
	})
	if err != nil {
		return nil, err
	}
	return toBizUser(&user), nil
}

func (r *userRepo) GetUserByUsername(ctx context.Context, username string) (*biz.User, error) {
	var user User
	err := r.redis.Take(ctx, fmt.Sprintf("users:username:%v", username), &user, userCacheTTL, func() error {
		return r.db.WithContext(ctx).Where("username = ?", username).First(&user).Error
	})
	if err != nil {
		return nil, err
	}
	return toBizUser(&user), nil
}

func (r *userRepo) GetUserByEmail(ctx context.Context, email string) (*biz.User, error) {
	var user User
	err := r.redis.Take(ctx, fmt.Sprintf("users:email:%v", email), &user, userCacheTTL, func() error {
		return r.db.WithContext(ctx).Where("email = ?", email).First(&user).Error
	})
	if err != nil {
		return nil, err
	}
	return toBizUser(&user), nil
}

func (r *userRepo) ListUsers(ctx context.Context, page, pageSize int32) ([]*biz.User, int32, error) {
	var users []User
	var total int64

	if err := r.db.WithContext(ctx).Model(&User{}).Count(&total).Error; err != nil {
		return nil, 0, err
	}

	offset := (page - 1) * pageSize
	if err := r.db.WithContext(ctx).
		Offset(int(offset)).
		Limit(int(pageSize)).
		Order("id DESC").
		Find(&users).Error; err != nil {
		return nil, 0, err
	}

	result := make([]*biz.User, 0, len(users))
	for _, u := range users {
		result = append(result, toBizUser(&u))
	}
	return result, int32(total), nil
}

func (r *userRepo) DeleteUser(ctx context.Context, id int64) error {
	// read-before-delete: get old record to invalidate cache keys
	old := &User{}
	if err := r.db.WithContext(ctx).First(old, id).Error; err != nil {
		return err
	}
	r.redis.Del(ctx, r.modelCacheKeys(old)...)
	return r.db.WithContext(ctx).Delete(&User{}, id).Error
}
