// Code generated by genmodel. DO NOT EDIT.

package data

import "time"


// User is the GORM model for the users table.
type User struct {
	Id int64 `gorm:"column:id;primaryKey;autoIncrement"`
	Username string `gorm:"column:username;size:64"`
	Password string `gorm:"column:password;size:256"`
	Email string `gorm:"column:email;size:128"`
	Phone string `gorm:"column:phone;size:32"`
	Nickname string `gorm:"column:nickname;size:64"`
	Avatar string `gorm:"column:avatar;size:256"`
	Status int32 `gorm:"column:status"`
	CreatedAt time.Time `gorm:"column:created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at"`
}

// TableName returns the table name.
func (User) TableName() string {
	return "users"
}
