// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire gen -tags "wireinject"
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos-layout-monolith/internal/conf"
	"github.com/go-kratos/kratos-layout-monolith/internal/model/user/biz"
	"github.com/go-kratos/kratos-layout-monolith/internal/model/user/data"
	"github.com/go-kratos/kratos-layout-monolith/internal/pkg/cache"
	"github.com/go-kratos/kratos-layout-monolith/internal/pkg/db"
	"github.com/go-kratos/kratos-layout-monolith/internal/pkg/lock"
	"github.com/go-kratos/kratos-layout-monolith/internal/server"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func initApp(bootstrap *conf.Bootstrap, logger log.Logger) (*appComponents, func(), error) {
	database := conf.DatabaseFromBootstrap(bootstrap)
	gormDB, cleanup, err := db.NewDatabase(database, logger)

	if err != nil {
		return nil, nil, err
	}
	redis := conf.RedisFromBootstrap(bootstrap)
	cacheRedis := cache.NewRedis(redis, logger)
	confServer := conf.ServerFromBootstrap(bootstrap)
	auth := conf.AuthFromBootstrap(bootstrap)
	jwt := conf.JwtFromBootstrap(bootstrap)
	httpServer, err := server.NewHTTPServer(confServer, auth, jwt, gormDB, cacheRedis, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cachedDB := cache.NewCachedDB(gormDB, cacheRedis, logger)
	userRepo := data.NewUserRepo(cachedDB, logger)
	locker := lock.NewRedisLocker(cacheRedis)
	userUsecase := biz.NewUserUsecase(userRepo, locker, logger)
	mainAppComponents, cleanup2, err := newAppComponents(logger, httpServer, userUsecase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return mainAppComponents, func() {
		cleanup2()
		cleanup()
	}, nil
}
