// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/go-kratos/kratos-layout-monolith/internal/conf"
	"github.com/go-kratos/kratos-layout-monolith/internal/model/user/biz"
	"github.com/go-kratos/kratos-layout-monolith/internal/model/user/service"

	v1 "github.com/go-kratos/kratos-layout-monolith/api/user/v1"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/transport/http"
)

// Injectors from wire.go:

// RegisterHTTP registers the user module's HTTP routes on the given server.
func RegisterHTTP(
	s *http.Server,
	uc *biz.UserUsecase,
	logger log.Logger,
	jwt *conf.Jwt,
) {
	srv := service.NewUserService(uc, jwt.Secret, jwt.Expire)
	v1.RegisterUserServiceHTTPServer(s, srv)
	log.NewHelper(logger).Infof("[user] routes registered")
}
