package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// modelGoTmpl generates the GORM model struct.
const modelGoTmpl = `// Code generated by genmodel. DO NOT EDIT.

package {{.PkgName}}

{{- if .HasTime}}

import "time"
{{end}}

// {{.Table.GoName}} is the GORM model for the {{.Table.Name}} table.
type {{.Table.GoName}} struct {
{{- range .Table.Columns}}
	{{.GoName}} {{.GoType}} {{.GormTag}}
{{- end}}
}

// TableName returns the table name.
func ({{.Table.GoName}}) TableName() string {
	return "{{.Table.Name}}"
}
`

// cacheRepoTmpl generates the cached repository implementation.
const cacheRepoTmpl = `// Code generated by genmodel. DO NOT EDIT.

package {{.PkgName}}

import (
	"context"
	"fmt"
	"time"

	"{{.BizImport}}"
	"github.com/go-kratos/kratos/v2/log"
	"gorm.io/gorm"
	"{{.CacheImport}}"
)

const (
	{{.CachePrefixVar}} = "{{.CachePrefix}}"
	{{.CacheTTLVar}}    = {{.CacheTTL}}
	{{.CacheJitterVar}} = {{.CacheJitter}}
)

type {{.RepoTypeName}} struct {
	db    *gorm.DB
	redis *cache.Redis
	log   *log.Helper
}

func new{{.Table.GoName}}Repo(db *gorm.DB, rds *cache.Redis, logger log.Logger) *{{.RepoTypeName}} {
	return &{{.RepoTypeName}}{
		db:    db,
		redis: rds,
		log:   log.NewHelper(logger),
	}
}

func (r *{{.RepoTypeName}}) modelCacheKeys(data *{{.Table.GoName}}) []string {
	keys := []string{
		fmt.Sprintf("%sid:%v", {{.CachePrefixVar}}, data.{{.Table.PrimaryKey.GoName}}),
	}
{{- range .UniqueIndexes}}
	keys = append(keys, fmt.Sprintf("{{.KeyPrefix}}%v", data.{{.GoName}}))
{{- end}}
	return keys
}

func toBizUser(u *{{.Table.GoName}}) *{{.BizTypeName}} {
	return &{{.BizTypeName}}{
{{- range .BizFromFields}}
	{{- if .IsTimeField}}
		{{.BizField}}: u.{{.GoField}}.Format("2006-01-02 15:04:05"),
	{{- else}}
		{{.BizField}}: u.{{.GoField}},
	{{- end}}
{{- end}}
	}
}

func fromBizUser(u *{{.BizTypeName}}) *{{.Table.GoName}} {
	return &{{.Table.GoName}}{
{{- range .BizToFields}}
	{{- if .IsTimeField}}
		{{.GoField}}: mustParseTime(u.{{.BizField}}),
	{{- else}}
		{{.GoField}}: u.{{.BizField}},
	{{- end}}
{{- end}}
	}
}

func mustParseTime(s string) time.Time {
	t, _ := time.ParseInLocation("2006-01-02 15:04:05", s, time.Local)
	return t
}

func (r *{{.RepoTypeName}}) {{.CreateMethodName}}(ctx context.Context, u *{{.BizTypeName}}) (*{{.BizTypeName}}, error) {
	user := fromBizUser(u)
	if err := r.db.WithContext(ctx).Create(user).Error; err != nil {
		return nil, err
	}
	r.redis.Set(ctx, fmt.Sprintf("%sid:%v", {{.CachePrefixVar}}, user.{{.Table.PrimaryKey.GoName}}), user, {{.CacheTTLVar}})
{{- range .UniqueIndexes}}
	r.redis.Set(ctx, fmt.Sprintf("{{.KeyPrefix}}%v", user.{{.GoName}}), user, {{$.CacheTTLVar}})
{{- end}}
	return toBizUser(user), nil
}

func (r *{{.RepoTypeName}}) {{.UpdateMethodName}}(ctx context.Context, u *{{.BizTypeName}}) (*{{.BizTypeName}}, error) {
	// read-before-write: get old record to invalidate old cache keys
	old := &{{.Table.GoName}}{}
	if err := r.db.WithContext(ctx).First(old, u.{{.Table.PrimaryKey.GoName}}).Error; err != nil {
		return nil, err
	}
	oldKeys := r.modelCacheKeys(old)

	if err := r.db.WithContext(ctx).Model(&{{.Table.GoName}}{ {{.Table.PrimaryKey.GoName}}: u.{{.Table.PrimaryKey.GoName}} }).Updates(map[string]any{
{{- range .UpdateColumns}}
		"{{.Name}}": u.{{.GoName}},
{{- end}}
	}).Error; err != nil {
		return nil, err
	}
	r.redis.Del(ctx, oldKeys...)

	// fetch updated record and re-cache
	new := &{{.Table.GoName}}{}
	if err := r.db.WithContext(ctx).First(new, u.{{.Table.PrimaryKey.GoName}}).Error; err != nil {
		return nil, err
	}
	for _, key := range r.modelCacheKeys(new) {
		r.redis.Set(ctx, key, new, {{.CacheTTLVar}})
	}
	return toBizUser(new), nil
}

func (r *{{.RepoTypeName}}) {{.GetByIDMethodName}}(ctx context.Context, id {{.Table.PrimaryKey.GoType}}) (*{{.BizTypeName}}, error) {
	var user {{.Table.GoName}}
	err := r.redis.Take(ctx, fmt.Sprintf("%sid:%v", {{.CachePrefixVar}}, id), &user, {{.CacheTTLVar}}, func() error {
		return r.db.WithContext(ctx).First(&user, id).Error
	})
	if err != nil {
		return nil, err
	}
	return toBizUser(&user), nil
}
{{- range .UniqueIndexes}}

func (r *{{$.RepoTypeName}}) {{$.GetByMethodName}}{{.GoName}}(ctx context.Context, {{untitle .GoName}} {{.GoType}}) (*{{$.BizTypeName}}, error) {
	var user {{$.Table.GoName}}
	err := r.redis.Take(ctx, fmt.Sprintf("{{.KeyPrefix}}%v", {{untitle .GoName}}), &user, {{$.CacheTTLVar}}, func() error {
		return r.db.WithContext(ctx).Where("{{.ColumnName}} = ?", {{untitle .GoName}}).First(&user).Error
	})
	if err != nil {
		return nil, err
	}
	return toBizUser(&user), nil
}
{{- end}}

func (r *{{.RepoTypeName}}) {{.ListMethodName}}(ctx context.Context, page, pageSize int32) ([]*{{.BizTypeName}}, int32, error) {
	var users []{{.Table.GoName}}
	var total int64

	if err := r.db.WithContext(ctx).Model(&{{.Table.GoName}}{}).Count(&total).Error; err != nil {
		return nil, 0, err
	}

	offset := (page - 1) * pageSize
	if err := r.db.WithContext(ctx).
		Offset(int(offset)).
		Limit(int(pageSize)).
		Order("id DESC").
		Find(&users).Error; err != nil {
		return nil, 0, err
	}

	result := make([]*{{.BizTypeName}}, 0, len(users))
	for _, u := range users {
		result = append(result, toBizUser(&u))
	}
	return result, int32(total), nil
}

func (r *{{.RepoTypeName}}) {{.DeleteMethodName}}(ctx context.Context, id {{.Table.PrimaryKey.GoType}}) error {
	// read-before-delete: get old record to invalidate cache keys
	old := &{{.Table.GoName}}{}
	if err := r.db.WithContext(ctx).First(old, id).Error; err != nil {
		return err
	}
	r.redis.Del(ctx, r.modelCacheKeys(old)...)
	return r.db.WithContext(ctx).Delete(&{{.Table.GoName}}{}, id).Error
}
`

// GenData holds template data for code generation.
type GenData struct {
	PkgName        string
	ModulePath     string
	BizImport      string
	CacheImport    string
	BizTypeName    string
	Table          *Table
	HasTime        bool
	CachePrefix    string
	CachePrefixVar string
	CacheTTL       string
	CacheTTLVar    string
	CacheJitter    string
	CacheJitterVar string
	RepoTypeName   string
	CreateMethodName  string
	UpdateMethodName  string
	GetByIDMethodName string
	GetByMethodName   string
	ListMethodName    string
	DeleteMethodName  string
	UpdateColumns     []Column
	BizFromFields     []BizField
	BizToFields       []BizField
	// UniqueIndexes with prefix data (used instead of Table.UniqueIndexes in templates).
	UniqueIndexes []UniqueIndexWithPrefix
}

// BizField maps a model field to its biz counterpart.
type BizField struct {
	BizField    string
	GoField     string
	IsTimeField bool
}

// UniqueIndexWithPrefix extends UniqueIndex with template data.
type UniqueIndexWithPrefix struct {
	Name       string
	ColumnName string
	GoName     string
	GoType     string
	KeyPrefix  string
}

// Generate reads a parsed Table and writes generated Go files to outDir.
func Generate(table *Table, pkgName, modulePath, bizImport, outDir string) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	data := buildGenData(table, pkgName, modulePath, bizImport)

	// Generate model file
	modelCode, err := executeTemplate("model", modelGoTmpl, data)
	if err != nil {
		return fmt.Errorf("model template: %w", err)
	}
	modelPath := filepath.Join(outDir, snakeToFileName(table.Name)+"_model_gen.go")
	if err := os.WriteFile(modelPath, []byte(modelCode), 0644); err != nil {
		return err
	}

	// Generate cache repo file
	repoCode, err := executeTemplate("cache_repo", cacheRepoTmpl, data)
	if err != nil {
		return fmt.Errorf("cache_repo template: %w", err)
	}
	repoPath := filepath.Join(outDir, snakeToFileName(table.Name)+"_cache_gen.go")
	if err := os.WriteFile(repoPath, []byte(repoCode), 0644); err != nil {
		return err
	}

	return nil
}

func buildGenData(table *Table, pkgName, modulePath, bizImport string) GenData {
	repoType := untitle(table.GoName) + "Repo"
	cacheVarPrefix := untitle(table.GoName) + "CachePrefix"
	cacheTTLVar := untitle(table.GoName) + "CacheTTL"
	cacheJitterVar := untitle(table.GoName) + "CacheJitter"

	hasTime := false
	for _, c := range table.Columns {
		if c.IsTime {
			hasTime = true
			break
		}
	}

	// Update columns: exclude PK, auto-inc, time fields, and password
	var updateCols []Column
	for _, c := range table.Columns {
		if c.IsPK || c.AutoIncre || c.IsTime || c.Name == "password" {
			continue
		}
		updateCols = append(updateCols, Column{
			Name:   c.Name,
			GoName: c.GoName,
		})
	}

	// Biz conversion fields
	var bizFromFields []BizField
	for _, c := range table.Columns {
		if c.Name == "password" {
			continue
		}
		bizFromFields = append(bizFromFields, BizField{
			BizField:    c.GoName,
			GoField:     c.GoName,
			IsTimeField: c.IsTime,
		})
	}

	var bizToFields []BizField
	for _, c := range table.Columns {
		if c.Name == "password" {
			continue
		}
		bizToFields = append(bizToFields, BizField{
			BizField:    c.GoName,
			GoField:     c.GoName,
			IsTimeField: c.IsTime,
		})
	}

	// Build unique indexes with prefix for template
	var uniqueIndexes []UniqueIndexWithPrefix
	for _, idx := range table.UniqueIndexes {
		uniqueIndexes = append(uniqueIndexes, UniqueIndexWithPrefix{
			Name:       idx.Name,
			ColumnName: idx.ColumnName,
			GoName:     toCamel(idx.ColumnName),
			GoType:     getColumnType(table, idx.ColumnName),
			KeyPrefix:  table.Name + ":" + idx.ColumnName + ":",
		})
	}

	return GenData{
		PkgName:    pkgName,
		ModulePath: modulePath,
		BizImport:  bizImport,
		CacheImport: modulePath + "/internal/pkg/cache",
		BizTypeName: "biz." + table.GoName,
		Table: &Table{
			Name:       table.Name,
			GoName:     table.GoName,
			Columns:    table.Columns,
			PrimaryKey: table.PrimaryKey,
		},
		HasTime:           hasTime,
		UniqueIndexes:     uniqueIndexes,
		CachePrefix:       table.Name + ":",
		CachePrefixVar:    cacheVarPrefix,
		CacheTTL:          "2 * time.Hour",
		CacheTTLVar:       cacheTTLVar,
		CacheJitter:       "30 * time.Minute",
		CacheJitterVar:    cacheJitterVar,
		RepoTypeName:      repoType,
		CreateMethodName:  "Create" + table.GoName,
		UpdateMethodName:  "Update" + table.GoName,
		GetByIDMethodName: "Get" + table.GoName + "ByID",
		GetByMethodName:   "Get" + table.GoName + "By",
		ListMethodName:    "List" + table.GoName + "s",
		DeleteMethodName:  "Delete" + table.GoName,
		UpdateColumns:     updateCols,
		BizFromFields:     bizFromFields,
		BizToFields:       bizToFields,
	}
}

func getColumnType(table *Table, colName string) string {
	for _, c := range table.Columns {
		if c.Name == colName {
			return c.GoType
		}
	}
	return "string"
}

func executeTemplate(name, tmplText string, data any) (string, error) {
	funcMap := template.FuncMap{
		"lower":   strings.ToLower,
		"untitle": untitle,
	}
	tmpl, err := template.New(name).Funcs(funcMap).Parse(tmplText)
	if err != nil {
		return "", err
	}
	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func snakeToFileName(name string) string {
	return strings.ToLower(name)
}
